[package]
name = "wasm-utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[dependencies.web-sys]
workspace = true
features = [
  "console",
]

# フィーチャーの定義
[features]
default = ["console_error_panic_hook", "wee_alloc"]